name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (optional)'
        required: false
        type: string

concurrency:
  group: release-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: read
  statuses: write

jobs:
  continuous:
    name: Continuous
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Determine version
        id: get_version
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "No version provided, calculating next version..."
          fi
      - uses: rmeneely/git-next-version@v1
        with:
          tag_pattern: '[0-9]*.[0-9]*.[0-9]*'
          increment: 'minor'
      - name: Set final version
        id: set_version
        run: |
          if [ -n "${{ steps.get_version.outputs.VERSION }}" ]; then
            echo "version=${{ steps.get_version.outputs.VERSION }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ env.NEXT_VERSION }}" >> $GITHUB_OUTPUT
          fi
      - name: "Generate Tuist Changelog"
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          owner: "tuist"
          repo: "XcodeGraph"
          configuration: ".github/changelog-configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check if there are categorized PRs
        id: check_prs
        run: |
          if [ "${{ steps.changelog.outputs.categorized_prs }}" = "0" ]; then
            echo "skip_next_steps=true" >> $GITHUB_OUTPUT
          else
            echo "skip_next_steps=false" >> $GITHUB_OUTPUT
          fi
      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        if: steps.check_prs.outputs.skip_next_steps != 'true'
        with:
          latest-version: ${{ steps.set_version.outputs.version }}
          release-notes: ${{ steps.changelog.outputs.changelog }}
          path-to-changelog: CHANGELOG.md
      - uses: stefanzweifel/git-auto-commit-action@v5
        if: steps.check_prs.outputs.skip_next_steps != 'true'
        with:
          commit_message: "Version ${{ steps.set_version.outputs.version }}"
          tagging_message: ${{ steps.set_version.outputs.version }}
          commit_options: '--allow-empty'
      - name: Create GitHub Release on the tuist/XcodeGraph repository
        if: steps.check_prs.outputs.skip_next_steps != 'true'
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          repository: tuist/XcodeGraph
          name: ${{ steps.set_version.outputs.version }}
          tag_name: ${{ steps.set_version.outputs.version }}
          body: ${{ steps.changelog.outputs.changelog }}
